### ISSUE TITLE
Is it possible to request MSGraph with AppId and Secret for console app

### ISSUE THREAD

**Issue by anomepani** [Azure-Samples/active-directory-dotnet-desktop-msgraph-v2#14]
I need authentication using AppId and Secret  so app can without prompting dialog popup. I have searched  a lot for repository but didn't find any sample running code .

**Comment by jmprieur** [comment]
@anomepani : did you look at this sample: https://github.com/azure-samples/active-directory-dotnetcore-daemon-v2. It's using https://msal-net-client-credentials

**Comment by anomepani** [comment]
Thank you for your quick response. Your provided solution work for me

**Comment by jmprieur** [comment]
Thanks for the update @anomepani
