### ISSUE TITLE
How to use Azure AD application roles & role claims

### ISSUE THREAD

**Issue by JimmyWuMadchester** [Azure-Samples/active-directory-dotnet-desktop-msgraph-v2#30]
If I add application roles in the **Manifest** as below, how can I get and validate the roles in the WPF app?

```
"appRoles": [
    {
      "allowedMemberTypes": [
        "User"
      ],
      "displayName": "Writer",
      "id": "d1c2ade8-98f8-45fd-aa4a-6d06b947c66f",
      "isEnabled": true,
      "description": "Writers Have the ability to create tasks.",
      "value": "Writer"
    },
    {
      "allowedMemberTypes": [
        "User"
      ],
      "displayName": "Observer",
      "id": "fcac0bdb-e45d-4cfc-9733-fbea156da358",
      "isEnabled": true,
      "description": "Observers only have the ability to view tasks and their statuses.",
      "value": "Observer"
    },
    {
      "allowedMemberTypes": [
        "User"
      ],
      "displayName": "Approver",
      "id": "fc803414-3c61-4ebc-a5e5-cd1675c14bbb",
      "isEnabled": true,
      "description": "Approvers have the ability to change the status of tasks.",
      "value": "Approver"
    },
    {
      "allowedMemberTypes": [
        "User"
      ],
      "displayName": "Admin",
      "id": "81e10148-16a8-432a-b86d-ef620c3e48ef",
      "isEnabled": true,
      "description": "Admins can manage roles and perform all task actions.",
      "value": "Admin"
    }
  ],
```

**Comment by jmprieur** [comment]
@JimmyWuMadchester you might want to have a look at this sample:
https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/tree/master/5-WebApp-AuthZ/5-1-Roles

**Comment by JimmyWuMadchester** [comment]
>This sample first leverages the ASP.NET Core OpenID Connect middleware to sign in the user. On the home page it displays the various claims that the user's ID Token contained. The ID token is used by the asp.net security middleware to build the ClaimsPrincipal, accessible via HttpContext.User in the code.

I'm familiar with the [sample](https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/tree/master/5-WebApp-AuthZ/5-1-Roles) uses ASP.NET middlewares to build the ClaimsPrincipal. And then you can use the Authorize attributes to check roles. However, in a WPF desktop application, is there any middlewares packages for the similar purpose so I can display different UI components based on users' claims?

**Comment by jmprieur** [comment]
@JimmyWuMadchester ,  are you saying that you want to extract, in a client (WPF desktop app), the roles which are in a token that this client for a particular Web API? 

If that's the case, then you should not do that because the access token you'll get is for the Web API only. It could even be encrypted and only the Web API would have the encryption key to decrypt it.

Can you explain what you are trying to achieve so that we propose the best solution.

**Comment by JimmyWuMadchester** [comment]
@jmprieur , I've registered my WPF app with Azure AD, and configured the appRoles in its Manifest. For example, Alice is assigned with Admin role while Bob is only a normal user. 

This WPF app has access to a list of different API resources that return different data depending on user roles assigned for this WPF app. So we don't need to manage individual user permissions to every API resources used. 

Also I'm thinking to use the id_token with roles claims returned by Azure AD to decide when to show Admin only features.

**Comment by jmprieur** [comment]
@JimmyWuMadchester : thanks for the explanations. This makes sense if you get the roles from the IDToken.

Are you then asking how to extract the roles from the IDToken? I'd suggest you look at https://www.nuget.org/packages/Microsoft.IdentityModel.JsonWebTokens/ and use the [JsonWebTokens](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/d4d6d3598952410ff96ef8f38c9ca9ce74bca8bf/src/Microsoft.IdentityModel.JsonWebTokens/JsonWebToken.cs#L53) constructor to with the AuthenticationResult.IDToken, and then call [.Claims](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/d4d6d3598952410ff96ef8f38c9ca9ce74bca8bf/src/Microsoft.IdentityModel.JsonWebTokens/JsonWebToken.cs#L158)

cc: @henrik-me (we should expose the IDTokenClaims in the Authentication result)

**Comment by jmprieur** [comment]
@JimmyWuMadchester : are you satisfied by the answer? do you want to close this issue?
