### ISSUE TITLE
How to use this sample in Visual studio 2013

### ISSUE THREAD

**Issue by abhisheknene007** [Azure-Samples/active-directory-dotnet-desktop-msgraph-v2#32]
Hi,
I am trying to use this repository into Visual studio 2013. Although i am getting error and project could not able to load.

Please suggest.

Note : We could not able to upgrade our visual studio version. due to dependancies.

**Comment by jmprieur** [comment]
@abhisheknene007 
You might want to tweak this line of the project:
https://github.com/Azure-Samples/active-directory-dotnet-desktop-msgraph-v2/blob/6dccca621af7683b128015be22c63f3d53234e51/active-directory-wpf-msgraph-v2/active-directory-wpf-msgraph-v2.csproj#L2

And maybe change the .NET framework version to a version of .NET supported by Visual Studio 2013
https://github.com/Azure-Samples/active-directory-dotnet-desktop-msgraph-v2/blob/6dccca621af7683b128015be22c63f3d53234e51/active-directory-wpf-msgraph-v2/active-directory-wpf-msgraph-v2.csproj#L11

All our samples were tested with Visual Studio 2017 and Visual Studio 2019 ... you're the first asking for VS 2013 ...

**Comment by jmprieur** [comment]
Closing as there was no answer.
Please reopen if you disagree.
