### ISSUE TITLE
Use WAM

### ISSUE THREAD

**Issue by bgavrilMS** [Azure-Samples/active-directory-dotnet-desktop-msgraph-v2#69]
We should showcase WAM in all public client samples.

**Comment by jmprieur** [comment]
@bgavrilMS 

This is done already: https://github.com/Azure-Samples/active-directory-dotnet-desktop-msgraph-v2/blob/f2549dc96f795a639a14e6b62fb06090a7f44481/active-directory-wpf-msgraph-v2/App.xaml.cs#L29
