### ISSUE TITLE
Mention prompt=select_account to avoid automatic re-signin

### ISSUE THREAD

**Issue by Fabian1337** [Azure-Samples/active-directory-dotnet-desktop-msgraph-v2#73]
should be same with ad

But after logged in once it will reuse my credentials and i cannot cancel or use different account somehow it is cached.

I Also tried to delete Internet Explorer Cache and Cookies but still it will login.

```c#
    Uri uri = new Uri("https://login.microsoftonline.com/common/oauth2/v2.0/authorize?" +
        "&client_id=" + ClientId +
        "&response_type=code" +
        "&redirect_uri=" + RedirectUri +
        "&response_mode=query" +
        "&scope=offline_access%20Files.Read%20Files.Read.All%20Files.Read.Selected%20Files.ReadWrite%20Files.ReadWrite.All%20User.Read");
    WebBrowser.Navigate(uri);
```

**Comment by Fabian1337** [comment]
https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-auth-code-flow

**Comment by jmprieur** [comment]
you might want to add a prompt, @Fabian1337 (for instance `prompt=select_account`)

**Comment by Fabian1337** [comment]
@jmprieur thanks for the fast answer, yes correctly therefore i closed the issue 👍 it was really hard to find this information :/

**Comment by jmprieur** [comment]
thanks for the feedback. Well add something in the README.md
